# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'EstacionApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for EstacionApp
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  target 'EstacionAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'EstacionAppUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
